<?php
namespace VOD\QubitArgentinaBundle\Services\Client\Movistar\Response;

use VOD\BaseBundle\Services\Client\Base\Response\BaseResponse;
use VOD\BaseBundle\Services\Client\User\Model\User;

class MovistarProvisionResponse extends BaseResponse
{
    public function isValidResponse()
    {
        return true === $this->getSuccess() && 1 === $this->countData();
    }

    public function countData()
    {
        return 1;
    }

     public function setData(\stdClass $data = null)
     {
         parent::setData($data); // TODO: Change the autogenerated stub

         $this->setSuccess($data->Success);

         $this->data = $data->Data;
     }
}